# Нарисуйте цифры от 1 до 3 , начиная от нижней точки цифры 1.

import turtle

turtle.pensize(2)

turtle.shape('turtle')
turtle.right(-90)
turtle.forward(100)
turtle.penup()
turtle.right(90)
turtle.forward(50)
turtle.pendown()
turtle.forward(70)
turtle.right(90)
turtle.forward(50)
turtle.right(90)
turtle.forward(70)
turtle.left(90)
turtle.forward(50)
turtle.left(90)
turtle.forward(70)
turtle.penup()
turtle.forward(50)
turtle.pendown()
turtle.forward(70)
turtle.left(90)
turtle.forward(50)
turtle.left(90)
turtle.forward(50)
turtle.left(180)
turtle.penup()
turtle.forward(50)
turtle.left(90)
turtle.pendown()
turtle.forward(50)
turtle.left(90)
turtle.forward(70)
turtle.hideturtle()


turtle.hideturtle()
turtle.exitonclick()